language: node_js
node_js:
  - 13

services:
  - docker

#pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed oliveth96/udagram-api-feed:v1
  - docker tag udagram-api-user oliveth96/udagram-api-user:v1
  - docker tag udagram-frontend:local oliveth96/udagram-frontend:v1
  - docker tag reverseproxy oliveth96/reverseproxy:v1


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oliveth96/udagram-api-feed:v1
  - docker push oliveth96/udagram-api-user:v1
  - docker push oliveth96/udagram-frontend:v1
  - docker push oliveth96/reverseproxy:v1